# Generated by Django 3.2.5 on 2021-07-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contactdetails_contactgroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='job',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
