# Generated by Django 3.2.5 on 2021-07-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_expand_contactdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='contactgroups',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Contact Group Name'),
        ),
    ]
