# Generated by Django 3.2.5 on 2021-07-01 15:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_contactpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionpage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('link', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('body', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.URLBlock())]))], blank=True),
        ),
    ]
