# Generated by Django 3.2.5 on 2021-07-01 16:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_regionpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionpage',
            name='menu',
            field=wagtail.core.fields.StreamField([('menu_item', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock()), ('link', wagtail.core.blocks.URLBlock())]))], blank=True),
        ),
        migrations.AddField(
            model_name='regionpage',
            name='standfirst',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
